import {test} from 'node:test';
import assert from 'node:assert/strict';
import handler from './api/notifications.js';
import {dateKey,DAY} from './data.js';
function call(url,method='GET',headers={host:'dashboard.vercel.app'},query){let code,body;handler({url,method,headers,query},{writeHead(s){code=s},end(v){body=JSON.parse(v)}});return {code,body}}
function scope(){const end=dateKey(Date.now()),start=dateKey(Date.now()-89*DAY),to=new Date(end+'T00:00:00');to.setDate(to.getDate()+1);return new URLSearchParams({tenant:'acme',start,end,from:new Date(start+'T00:00:00').toISOString(),to:to.toISOString()})}
test('serverless search validates scope and returns channel details',()=>{const r=call('/api/notifications?'+scope());assert.equal(r.code,200);assert.ok(r.body.notifications.length);assert.ok(r.body.notifications.every(n=>n.tenant==='acme'&&n.deliveries.length));assert.equal(call('/api/notifications').code,400);assert.equal(call('/api/notifications?tenant=acme').code,400);assert.equal(call('/api/notifications?'+scope(),'GET',{host:'dashboard.vercel.app',origin:'https://other.example'}).code,403)});
test('serverless rewrites support retry, reject duplicate and isolate tenants',()=>{const rows=call('/api/notifications?'+scope()).body.notifications,n=rows.find(n=>n.status==='Failed'&&n.errorType!=='TemplateError');const route='/api/notifications?tenant=acme&notificationId='+n.id+'&action=reprocess';const result=call(route,'POST',{host:'dashboard.vercel.app',origin:'https://dashboard.vercel.app'});assert.equal(result.code,200);assert.equal(result.body.notification.status,'Retry');assert.equal(call(route,'POST').code,409);assert.equal(call('/api/notifications?tenant=ramco&notificationId='+n.id).code,404);assert.equal(call('/api/notifications/'+n.id+'?tenant=acme').body.notification.status,'Retry')});
test('template failures cannot be reprocessed on the server',()=>{const n=call('/api/notifications?'+scope()).body.notifications.find(n=>n.status==='Failed'&&n.errorType==='TemplateError');assert.equal(call('/api/notifications/'+n.id+'/reprocess?tenant=acme','POST').code,409)});
